server:
  port: 8081

spring:
  datasource:
    username: root
    password: rootdawS
    url: jdbc:mysql://114.67.168.56:3306/clapsql_website?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # &useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/clapsql/mapper/*.xml

# 日志配置
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework: DEBUG
#      org:
#        mybatis: DEBUG
